### ISSUE TITLE
DeCodi issue

### ISSUE THREAD

**Issue by EnriqueDominguez** [Shafledome/calculadora-universalidad#1]
DeCodiReturn function should be modified in order to compute the correct length (`longitud`) of `z`
Lines 908-909:

    console.log("Con z: " + z + " y una longitud de: " + longitud(z+1n));
    for (var i = 1n; i <= longitud(z+1n); i++) { // desde 1 hasta la longitud de z+1, calculamos las sentencias

**Comment by Shafledome** [comment]
Fixed up. Closing issue.
